### ISSUE TITLE
can disabledDates option be a function ?

### ISSUE THREAD

**Issue by pounard** [icehaunter/vue3-datepicker#31] opened 2021-03-12 14:14 UTC
This may sound like a stupid question, but one need I do have right now is the ability to disable all weekend (saturdays and sundays) in some calendars.

Is that possible ?

**Comment by Tcrussell436** [comment] 2021-03-20 04:13
The disabledDates prop is an array of Dates, PR open for adding a disable weekends prop

**Comment by pounard** [comment] 2021-03-21 08:44
@Tcrussell436 nice thanks, but having a date filter function would also be a very good idea, for example we work with a client for which we do sometime compute allowed dates using french working days computation formula, with sometime client-specific additions to that formula.

Having a weekend filter is a good step forward, I like it, but I think it's not possible to cover all possible use case using utility options, having a generic function filter here for developers to hook into would be a very good idea to make it future-proof.

Overall, using a generic filter function mecanism, you could implement the weekend filter in a generic fashion.

**Comment by icehaunter** [comment] 2021-07-01 18:53
Great request, should be very easy to add - contributions welcome!

**Comment by icehaunter** [comment] 2021-07-01 18:58
Duplicate of #17

**Closed by icehaunter** 2021-07-01 18:58 UTC
Labels: contribution wanted, enhancement, good first issue
