### ISSUE TITLE
Can I open the calendar by clicking on an icon

### ISSUE THREAD

**Issue by nehalfirdausi** [icehaunter/vue3-datepicker#40] opened 2021-06-02 15:03 UTC
Good afternoon,

I am trying to use vue3-datepicker and my UX requirement is to open the calendar by clicking on an icon and not directly on the input field.

Please advice.

Thank you for your support.

Regards

**Comment by icehaunter** [comment] 2021-07-01 18:50
Hello, sorry, this project doesn't currently support this functionality. It should be easy to add, however, I'm not adding features at the moment. I'd love a contribution though!

**Comment by icehaunter** [comment] 2021-07-01 18:57
Actually, this is a duplicate of #6

**Closed** 2021-07-01 18:57 UTC
Labels: contribution wanted, enhancement, good first issue
